// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgi2h8F18fJ-itb2_9BURGMywMp5RSs_Q',
    appId: '1:110589546991:web:3fd77913a02d3b53cba61a',
    messagingSenderId: '110589546991',
    projectId: 'dhex-d9bc6',
    authDomain: 'dhex-d9bc6.firebaseapp.com',
    storageBucket: 'dhex-d9bc6.firebasestorage.app',
    measurementId: 'G-KGRZ1TPVHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6tlzyuQrMbISTVm445ST9xo9Ovw478k',
    appId: '1:110589546991:android:20ce2c880b91837acba61a',
    messagingSenderId: '110589546991',
    projectId: 'dhex-d9bc6',
    storageBucket: 'dhex-d9bc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq6NoK-RXav_7xAbJm93C3JzpDGW6r9e8',
    appId: '1:110589546991:ios:81c8013a18b28054cba61a',
    messagingSenderId: '110589546991',
    projectId: 'dhex-d9bc6',
    storageBucket: 'dhex-d9bc6.firebasestorage.app',
    iosBundleId: 'com.example.dhexProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq6NoK-RXav_7xAbJm93C3JzpDGW6r9e8',
    appId: '1:110589546991:ios:81c8013a18b28054cba61a',
    messagingSenderId: '110589546991',
    projectId: 'dhex-d9bc6',
    storageBucket: 'dhex-d9bc6.firebasestorage.app',
    iosBundleId: 'com.example.dhexProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgi2h8F18fJ-itb2_9BURGMywMp5RSs_Q',
    appId: '1:110589546991:web:0f1104ec03c05299cba61a',
    messagingSenderId: '110589546991',
    projectId: 'dhex-d9bc6',
    authDomain: 'dhex-d9bc6.firebaseapp.com',
    storageBucket: 'dhex-d9bc6.firebasestorage.app',
    measurementId: 'G-YZPKJ4WQ9L',
  );
}
